import { createSlice } from '@reduxjs/toolkit';

// This file defines a Redux slice for managing the shopping cart state in an e-commerce application.
const initialState = {
    cartItems: [],
  };

// This slice manages the cart state
const CartSlice = createSlice({
    name: 'cart',
    initialState,
    reducers: {
      // Actions to manipulate the cart state
        addItemToCart(state, action) {
            const existingItem = state.cartItems.find(item => item.id === action.payload.id);
            if (existingItem) {
              existingItem.quantity += 1;
            } else {
              state.cartItems.push({ ...action.payload, quantity: 1 });
            }
          },
      // Actions to remove an item from the cart, clear the cart, and adjust item quantities
      
          removeItemFromCart(state, action) {
            state.cartItems = state.cartItems.filter(item => item.id !== action.payload);
          },
          clearCart(state) {
            state.cartItems = [];
          },
          // Action to increase item quantity
          increaseItemQuantity(state, action) {
            const itemToIncrease = state.cartItems.find(item => item.id === action.payload);
            if (itemToIncrease) {
              itemToIncrease.quantity += 1;
            }
          },
          // Action to decrease item quantity, ensuring it doesn't go below 1
          decreaseItemQuantity(state, action) {
            const itemToDecrease = state.cartItems.find(item => item.id === action.payload);
            if (itemToDecrease && itemToDecrease.quantity > 1) {
              itemToDecrease.quantity -= 1;
            }
          },


    }
});
// Export the actions generated by createSlice for use in components
export const {
    addItemToCart,
    removeItemFromCart,
    clearCart,
    increaseItemQuantity,
    decreaseItemQuantity,
  } = CartSlice.actions; 
  // Export the actions for use in components
  export default CartSlice.reducer;